project:
  type: website
  output-dir: docs
  resources:
    - materials/MathCamp/**

website:
  title: "Yue Yu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching
      - href: research.qmd
        text: Research
    right:
      - text: Email
        href: mailto:yu78@ucsb.edu
  page-footer:
    left: "© Yue Yu"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
